# Site settings
title: Code Laboratory
email: stephenianroberts@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  This site contains my personal notes, snippets and other technical ephemera.
baseurl: "/laboratory" # the subpath of your site, e.g. /blog/
url: "http://csrhau.github.io" # the base hostname & protocol for your site
twitter_username: nastyste
github_username:  csrhau

# Build settings
markdown: kramdown
host: 0.0.0.0
